# JDBC properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/university-demo?useSSL=false&serverTimezone=UTC
spring.datasource.username=unidemo
spring.datasource.password=unidemo

# Web view config
#
spring.mvc.view.prefix: /WEB-INF/view/
spring.mvc.view.suffix: .jsp
